version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: changelog
    ports:
      - "5432:5432"                      # Проброс порта
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Персистентное хранилище данных

volumes:
  postgres_data: